<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0;'); // Desactivamos la revisión de claves foráneas
        DB::table('models')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1;'); // Acivamos la revisión de claves foráneas

        $sql= "INSERT INTO models (make_id,name) VALUES
                (1,'MDX'),
                (1,'TLX'),
                (2,'ENCLAVE'),
                (2,'ENCORE'),
                (2,'ENVISION'),
                (2,'LACROSSE'),
                (2,'REGAL'),
                (2,'RENDEZVOUS'),
                (2,'VERANO'),
                (3,'ATS'),
                (3,'CTS'),
                (3,'ESCALADE'),
                (3,'SRX'),
                (3,'XT5'),
                (3,'XTS'),
                (4,'CAMARO'),
                (4,'COLORADO'),
                (4,'CRUZE'),
                (4,'CRUZE LIMITED'),
                (4,'EQUINOX'),
                (4,'IMPALA'),
                (4,'MALIBU'),
                (4,'SILVERADO'),
                (4,'SILVERADO 1500'),
                (4,'SILVERADO 2500HD'),
                (4,'SONIC'),
                (4,'SUBURBAN'),
                (4,'TAHOE'),
                (4,'TRAVERSE'),
                (4,'TRAX'),
                (5,'200'),
                (5,'300'),
                (5,'PACIFICA'),
                (5,'TOWN & COUNTRY'),
                (6,'AVENGER'),
                (6,'CHALLENGER'),
                (6,'CHARGER'),
                (6,'DURANGO'),
                (6,'GRAND CARAVAN'),
                (6,'JOURNEY'),
                (6,'RAM'),
                (6,'RAM 1500'),
                (7,'ECOSPORT'),
                (7,'EDGE'),
                (7,'ESCAPE'),
                (7,'EXPEDITION'),
                (7,'EXPEDITION EL'),
                (7,'EXPLORER'),
                (7,'F 150'),
                (7,'F-150'),
                (7,'F-250 SD'),
                (7,'F-350 SD'),
                (7,'FLEX'),
                (7,'FOCUS'),
                (7,'FUSION'),
                (7,'FUSION ENERGI'),
                (7,'MUSTANG'),
                (7,'TAURUS'),
                (8,'G80'),
                (9,'ACADIA'),
                (9,'CANYON'),
                (9,'SIERRA'),
                (9,'SIERRA 1500'),
                (9,'TERRAIN'),
                (9,'YUKON'),
                (9,'YUKON DENALI'),
                (9,'YUKON XL'),
                (10,'ACCORD'),
                (10,'CIVIC'),
                (10,'CR-V'),
                (10,'FIT'),
                (10,'HR-V'),
                (10,'ODYSSEY'),
                (10,'PILOT'),
                (10,'RIDGELINE'),
                (11,'ACCENT'),
                (11,'AZERA'),
                (11,'ELANTRA'),
                (11,'ELANTRA GT'),
                (11,'GENESIS'),
                (11,'SANTA FE'),
                (11,'SANTA FE SPORT'),
                (11,'SONATA'),
                (11,'TUCSON'),
                (11,'VELOSTER'),
                (12,'EX'),
                (12,'G SEDAN'),
                (12,'Q50'),
                (12,'QX56'),
                (12,'QX60'),
                (12,'QX80'),
                (13,'CHEROKEE'),
                (13,'COMPASS'),
                (13,'GRAND CHEROKEE'),
                (13,'LIBERTY'),
                (13,'PATRIOT'),
                (13,'RENEGADE'),
                (13,'WRANGLER'),
                (13,'WRANGLER JK'),
                (14,'CADENZA'),
                (14,'FORTE'),
                (14,'K900'),
                (14,'OPTIMA'),
                (14,'RIO'),
                (14,'SEDONA'),
                (14,'SORENTO'),
                (14,'SOUL'),
                (14,'SPORTAGE'),
                (15,'ES'),
                (15,'ES 350'),
                (15,'GX 460'),
                (15,'IS'),
                (15,'NX 200T'),
                (15,'RX 350'),
                (16,'MKC'),
                (16,'NAVIGATOR'),
                (17,'CX 9'),
                (17,'CX-3'),
                (17,'CX-5'),
                (17,'CX-9'),
                (17,'MAZDA3'),
                (17,'MAZDA6'),
                (18,'MIRAGE G4'),
                (18,'OUTLANDER'),
                (18,'OUTLANDER SPORT'),
                (19,'ALTIMA'),
                (19,'ARMADA'),
                (19,'FRONTIER'),
                (19,'JUKE'),
                (19,'MAXIMA'),
                (19,'MURANO'),
                (19,'MURANO HYBRID'),
                (19,'PATHFINDER'),
                (19,'ROGUE'),
                (19,'ROGUE SELECT'),
                (19,'ROGUE SPORT'),
                (19,'SENTRA'),
                (19,'TITAN'),
                (19,'TITAN XD'),
                (19,'VERSA'),
                (19,'VERSA NOTE'),
                (20,'1500'),
                (20,'1500 CLASSIC'),
                (20,'2500'),
                (21,'4 RUNNER'),
                (21,'4-RUNNER'),
                (21,'4RUNNER'),
                (21,'AVALON'),
                (21,'C-HR'),
                (21,'CAMRY'),
                (21,'COROLLA'),
                (21,'HIGHLANDER'),
                (21,'RAV4'),
                (21,'SEQUOIA'),
                (21,'SIENNA'),
                (21,'TACOMA'),
                (21,'TUNDRA'),
                (21,'VENZA'),
                (22,'JETTA'),
                (23,'XVS1300CU')";
        DB::update ($sql);
    }
}
