INSERT INTO `teams` (`sport_id`, `name`, `alias`, `short`, `logotipo`, `request_score`, `active`) VALUES
	(1, 'Argentina', 'Argentina', 'Argent', NULL, 0, 1),
	(1, 'Países Bajos', 'Países Bajos', 'Países', NULL, 0, 1),
	(1, 'Uruguay', 'Uruguay', 'Urugua', NULL, 0, 1),
	(1, 'Bélgica', 'Bélgica', 'Bélgic', NULL, 0, 1),
	(1, 'Serbia', 'Serbia', 'Serbia', NULL, 0, 1),
	(1, 'Arabia Saudí', 'Arabia Saudí', 'Arabia', NULL, 0, 1),
	(1, 'Ecuador', 'Ecuador', 'Ecuado', NULL, 0, 1),
	(1, 'Croacia', 'Croacia', 'Croaci', NULL, 0, 1),
	(1, 'Suiza', 'Suiza', 'Suiza', NULL, 0, 1),
	(1, 'Japón', 'Japón', 'Japón', NULL, 0, 1),
	(1, 'Portugal', 'Portugal', 'Portug', NULL, 0, 1),
	(1, 'Francia', 'Francia', 'Franci', NULL, 0, 1),
	(1, 'Inglaterra', 'Inglaterra', 'Inglat', NULL, 0, 1),
	(1, 'Túnez', 'Túnez', 'Túnez', NULL, 0, 1),
	(1, 'Alemania', 'Alemania', 'Aleman', NULL, 0, 1),
	(1, 'Estados Unidos', 'Estados Unidos', 'Estado', NULL, 1, 1),
	(1, 'España', 'España', 'España', NULL, 0, 1),
	(1, 'Ghana', 'Ghana', 'Ghana', NULL, 0, 1),
	(1, 'Irán', 'Irán', 'Irán', NULL, 0, 1),
	(1, 'Brasil', 'Brasil', 'Brasil', NULL, 0, 1),
	(1, 'Gales', 'Gales', 'Gales', NULL, 0, 1),
	(1, 'Marruecos', 'Marruecos', 'Marrue', NULL, 0, 1),
	(1, 'Canadá', 'Canadá', 'Canadá', NULL, 0, 1),
	(1, 'México', 'México', 'México', NULL, 1, 1),
	(1, 'Polonia', 'Polonia', 'Poloni', NULL, 0, 1),
	(1, 'Australia', 'Australia', 'Austra', NULL, 0, 1),
	(1, 'Dinamarca', 'Dinamarca', 'Dinama', NULL, 0, 1),
	(1, 'Qatar', 'Qatar', 'Qatar', NULL, 0, 1),
	(1, 'Costa Rica', 'Costa Rica', 'Costa ', NULL, 0, 1),
	(1, 'Senegal', 'Senegal', 'Senega', NULL, 0, 1),
	(3, 'Corea del Sur', 'Corea del Sur', 'Corea ', NULL, 0, 1),
	(1, 'Camerún', 'Camerún', 'Camerú', NULL, 0, 1);
